// chx-gen connects to a ClickHouse server and generates a Go source file
// containing embedded function metadata for the chx CLI.
//
// Usage:
//
//	go run ./cmd/chx-gen -connstr "clickhouse://default@localhost:9000/default" -out internal/functions/generated.go
package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"strings"
	"text/template"
	"time"

	"github.com/vahid-sohrabloo/chcli/internal/conn"
)

type FuncInfo struct {
	Name         string `json:"name"`
	IsAggregate  bool   `json:"is_aggregate"`
	Description  string `json:"description"`
	Syntax       string `json:"syntax"`
	Arguments    string `json:"arguments"`
	ReturnedVal  string `json:"returned_value"`
	IntroducedIn string `json:"introduced_in"`
	Categories   string `json:"categories"`
}

var goTemplate = template.Must(template.New("functions").Parse(`// Code generated by chx-gen. DO NOT EDIT.
// Generated from ClickHouse {{ .ServerVersion }} on {{ .Timestamp }}
//
// Regenerate: go run ./cmd/chx-gen -connstr "clickhouse://default@localhost:9000/default"

package functions

// BuiltinFunctions contains all known ClickHouse functions.
// Generated from ClickHouse {{ .ServerVersion }}.
var BuiltinFunctions = []FunctionDef{
{{- range .Functions }}
	{
		Name:         {{ printf "%q" .Name }},
		IsAggregate:  {{ .IsAggregate }},
		Description:  {{ printf "%q" .Description }},
		Syntax:       {{ printf "%q" .Syntax }},
		Arguments:    {{ printf "%q" .Arguments }},
		ReturnedVal:  {{ printf "%q" .ReturnedVal }},
		IntroducedIn: {{ printf "%q" .IntroducedIn }},
		Categories:   {{ printf "%q" .Categories }},
	},
{{- end }}
}
`))

func main() {
	connStr := flag.String("connstr", "clickhouse://default@localhost:9000/default", "ClickHouse connection string")
	outPath := flag.String("out", "internal/functions/generated.go", "Output Go file path")
	flag.Parse()

	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	fmt.Printf("Connecting to %s...\n", *connStr)
	c, err := conn.Connect(ctx, *connStr)
	if err != nil {
		fmt.Fprintf(os.Stderr, "connect: %v\n", err)
		os.Exit(1)
	}
	defer c.Close()

	serverVersion := c.ServerVersion()
	fmt.Printf("Connected to ClickHouse %s\n", serverVersion)

	// Try full metadata query first, fall back to basic.
	sql := `SELECT name, is_aggregate, description, syntax, arguments, returned_value, introduced_in, categories
		FROM system.functions WHERE origin = 'System' ORDER BY name`

	result, err := c.QueryAll(ctx, sql)
	if err != nil {
		// Fall back without extended fields.
		fmt.Println("Falling back to basic function query...")
		sql = `SELECT name, is_aggregate FROM system.functions WHERE origin = 'System' ORDER BY name`
		result, err = c.QueryAll(ctx, sql)
		if err != nil {
			fmt.Fprintf(os.Stderr, "query: %v\n", err)
			os.Exit(1)
		}
	}

	numCols := len(result.Columns)
	functions := make([]FuncInfo, 0, len(result.Rows))
	for _, row := range result.Rows {
		fi := FuncInfo{
			Name:        row[0],
			IsAggregate: row[1] == "1",
		}
		if numCols >= 3 && len(row) >= 3 {
			fi.Description = cleanString(row[2])
		}
		if numCols >= 4 && len(row) >= 4 {
			fi.Syntax = cleanString(row[3])
		}
		if numCols >= 5 && len(row) >= 5 {
			fi.Arguments = cleanString(row[4])
		}
		if numCols >= 6 && len(row) >= 6 {
			fi.ReturnedVal = cleanString(row[5])
		}
		if numCols >= 7 && len(row) >= 7 {
			fi.IntroducedIn = row[6]
		}
		if numCols >= 8 && len(row) >= 8 {
			fi.Categories = row[7]
		}
		functions = append(functions, fi)
	}

	fmt.Printf("Found %d functions\n", len(functions))

	f, err := os.Create(*outPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "create file: %v\n", err)
		os.Exit(1)
	}
	defer f.Close()

	data := struct {
		ServerVersion string
		Timestamp     string
		Functions     []FuncInfo
	}{
		ServerVersion: serverVersion,
		Timestamp:     time.Now().Format("2006-01-02 15:04:05"),
		Functions:     functions,
	}

	if err := goTemplate.Execute(f, data); err != nil {
		fmt.Fprintf(os.Stderr, "template: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s (%d functions)\n", *outPath, len(functions))

	// Also export as JSON for reference.
	jsonPath := strings.TrimSuffix(*outPath, ".go") + ".json"
	jf, err := os.Create(jsonPath)
	if err == nil {
		enc := json.NewEncoder(jf)
		enc.SetIndent("", "  ")
		enc.Encode(functions)
		jf.Close()
		fmt.Printf("Also exported %s\n", jsonPath)
	}
}

func cleanString(s string) string {
	// Collapse multiple newlines, trim.
	s = strings.TrimSpace(s)
	// Take first paragraph only for descriptions.
	if idx := strings.Index(s, "\n\n"); idx > 0 {
		s = s[:idx]
	}
	return s
}
