// Package functions provides embedded ClickHouse function metadata.
// The function list is generated by `go run ./cmd/chcli-gen` and stored
// in generated.go. This package provides helpers to filter functions
// by ClickHouse server version.
package functions

import (
	"strconv"
	"strings"
)

// FunctionDef holds metadata for a built-in ClickHouse function.
type FunctionDef struct {
	Name         string
	IsAggregate  bool
	Description  string
	Syntax       string
	Arguments    string
	ReturnedVal  string
	IntroducedIn string // version like "21.1" — empty if unknown
	Categories   string
}

// ForVersion returns functions available in the given ClickHouse version.
// Version format: "24.3.1" or "25.3.3". If version is empty, all functions
// are returned.
func ForVersion(version string) []FunctionDef {
	if version == "" {
		return BuiltinFunctions
	}

	major, minor := parseVersion(version)
	if major == 0 {
		return BuiltinFunctions
	}

	var result []FunctionDef
	for _, f := range BuiltinFunctions {
		if f.IntroducedIn == "" {
			// Unknown introduction version — include it.
			result = append(result, f)
			continue
		}
		fMajor, fMinor := parseVersion(f.IntroducedIn)
		if fMajor == 0 || fMajor < major || (fMajor == major && fMinor <= minor) {
			result = append(result, f)
		}
	}
	return result
}

// Lookup returns the function definition for the given name, or nil.
func Lookup(name string) *FunctionDef {
	lower := strings.ToLower(name)
	for i := range BuiltinFunctions {
		if strings.ToLower(BuiltinFunctions[i].Name) == lower {
			return &BuiltinFunctions[i]
		}
	}
	return nil
}

func parseVersion(v string) (major, minor int) {
	parts := strings.SplitN(v, ".", 3)
	if len(parts) >= 1 {
		major, _ = strconv.Atoi(parts[0])
	}
	if len(parts) >= 2 {
		minor, _ = strconv.Atoi(parts[1])
	}
	return
}
